
import { db } from '../db';
import { systemLogs, requestLogs } from '../db/schema';
import { logger } from './logger';

async function seed() {
    // Mock data removed at user request.
    // Real system logs will be generated by the app.
    console.log("Seeding disabled (Mock data removed).");
}

export default seed;
