global:
  resolve_timeout: 5m

route:
  receiver: "warning-webhook"
  group_by: ["alertname", "service", "severity", "provider"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h
  routes:
    - receiver: "warning-webhook"
      matchers:
        - severity="warning"
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      continue: false
    - receiver: "critical-webhook"
      matchers:
        - severity="critical"
      group_wait: 10s
      group_interval: 2m
      repeat_interval: 30m
      continue: false

receivers:
  - name: "warning-webhook"
    webhook_configs:
      - url: "http://host.docker.internal:18080/alertmanager/warning"
        send_resolved: true

  - name: "critical-webhook"
    webhook_configs:
      - url: "http://host.docker.internal:18080/alertmanager/critical"
        send_resolved: true

